/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.HospitalData;
import Model.InsuranceAgencyData;
import Model.SupplierData;
import Model.User;
import Model.UserData;
import Model.pharmacyData;
import SQLConnection.SQLConnection;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author lokeshbalamurugan
 */
public class AdminCreateUser extends javax.swing.JPanel {

    /**
     * Creates new form AdminCreateUser
     */
    UserData userData;
    public AdminCreateUser(UserData userData) {
        initComponents();
        this.userData = userData;
            jLabel15.setVisible(false);
            jComboBox1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtPhnNo = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        OrgComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("Personal Information");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FIRST NAME :");

        jLabel5.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LAST NAME :");

        jLabel6.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATE OF BIRTH :");

        jLabel7.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GENDER :");

        jLabel8.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSWORD :");

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USERNAME :");

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PHONE NUMBER :");

        jLabel11.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("EMAIL :");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to respond" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(82, 82, 82)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPhnNo)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(132, 132, 132))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel12.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Other Information");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));

        jLabel13.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 204, 255));
        jLabel13.setText("Organisation :");

        OrgComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "System", "Hospital", "Pharmacy", "Supplier", "Insurance" }));
        OrgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 204, 255));
        jLabel14.setText("Role :");

        RoleComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoleComboBoxMouseClicked(evt);
            }
        });
        RoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleComboBoxActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 204, 255));
        jLabel15.setText("Select one :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OrgComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RoleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(OrgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(RoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(1056, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username, password, name, role, org, orgName, dob, gender, email, number;
        username = txtUsername.getText();
        password = txtPassword.getText();
        name = txtFName.getText()+" "+txtLName.getText();
        dob = txtDOB.getText();
        gender = jComboBox2.getSelectedItem().toString();
        email = txtEmail.getText();
        number = txtPhnNo.getText();
        org = OrgComboBox.getSelectedItem().toString();
        role = RoleComboBox.getSelectedItem().toString();
        if(org == "Patient"){
        orgName = "Patient";
    }else if(org == "System"){
        orgName = "System";
    }else{
        orgName = jComboBox1.getSelectedItem().toString();
    }
        
        //validation
        //username
        try{
                    //username
            if(username.isEmpty()){
                throw new InputMismatchException("Invalid username");
            }
            else{
                    Connection con=SQLConnection.dbconnector();
                    //JOptionPane.showMessageDialog(this, "connection Sucess");
                    Statement stmt=con.createStatement();
//                    String query = "USE test_app;";
//                    stmt.executeUpdate(query);
                    String query="select username,password,role from UserData where username='"+username+"';";

                    ResultSet rst=stmt.executeQuery(query);
                     if (rst.next())
                    {
                        throw new InputMismatchException("Invalid username");
                        //String role=rst.getString("role_");
                        //JOptionPane.showMessageDialog(this, "Login Sucess", "", HEIGHT);
                        //JOptionPane.showMessageDialog(this, role, query, HEIGHT);

                    }
                

                   
                
            }
            //password
            if(password.isEmpty() || password.length()<3){
                throw new InputMismatchException("Invalid password");
            }
            //name
            if(txtFName.getText().length()<4 || txtLName.getText().length() <4){
                throw new InputMismatchException("Invalid FirstName and LastName");
            }
            //number
            Pattern mobilePattern = Pattern.compile("(0/91)?[7-9][0-9]{9}");  
            Matcher matcher = mobilePattern.matcher(number);  
            if(!matcher.matches()){
                throw new InputMismatchException("Invalid Contact Number");
            }
            //email
            Pattern emailPattern = Pattern.compile("^(.+)@(.+)$");
            matcher = emailPattern.matcher(email);
            if(!matcher.matches()){
                throw new InputMismatchException("Invalid Email");   
            }
            User p = userData.addNewUser();
            p.setName(name);
            p.setUsername(username);
            p.setRole(role);
            p.setOrg(org);
            p.setPassword(password);
            p.setOrgName(orgName);
            boolean res = userData.createUserInDb(p);
            if(!res){
                JOptionPane.showMessageDialog(this,"retry" , "warning", HEIGHT);
            }
            clearData();
            
                    
            
        }
        catch(SQLException e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(this,"retry" , "warning", HEIGHT);
        }
        catch(InputMismatchException e){
            JOptionPane.showMessageDialog(this,e.getMessage() , "warning", HEIGHT);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void OrgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgComboBoxActionPerformed
        // TODO add your handling code here
                String[] roleArray = null;
        //JOptionPane.showMessageDialog(this,"hi");                  
                        
                //patient, doctor, hospitalAdmin, insuranceAdmin, insuranceEmp, insuranceFinance, pharmacyAdmin, supplier, sysAdmin
                //String[]
        String org_ = OrgComboBox.getSelectedItem().toString();
        //JOptionPane.showMessageDialog(this,org_);
        if (org_!= null){
            String[] patient ={"patient"};
            String[] hospital ={"doctor", "hospitalAdmin"};
            String[] system ={"systemAdmin"};
            String[] insurance ={"insuranceAdmin","insuranceEmployee","insuranceFinance"};
            String[] supplier ={"supplier"};
            String[] pharmacy ={"pharmacyAdmin"};
                    //ArrayList<community> commData= communityData.SearchCommunity(jComboBox2.getSelectedItem().toString(), "community");
            switch (org_){
                case "Patient":
                    roleArray = new String[patient.length];
                    for(int i = 0; i < roleArray.length; i++) {
                        roleArray[i] = patient[i];
                        //JOptionPane.showMessageDialog(this,roleArray[i]);
                    }
                    break;
                case "System":
                    
                    roleArray = new String[system.length];
                    for(int i = 0; i < roleArray.length; i++) {
                        roleArray[i] = system[i];
                        //JOptionPane.showMessageDialog(this,array[i]);
                    }
                    break;
                case "Hospital":
                    roleArray = new String[hospital.length];
                    for(int i = 0; i < roleArray.length; i++) {
                        roleArray[i] = hospital[i];
                        //JOptionPane.showMessageDialog(this,array[i]);
                    }
                    
                    break;
                case "Pharmacy":
                    roleArray = new String[pharmacy.length];
                    for(int i = 0; i < roleArray.length; i++) {
                        roleArray[i] = pharmacy[i];
                        //JOptionPane.showMessageDialog(this,array[i]);
                    }
                    break;
                case "Supplier":
                    roleArray = new String[supplier.length];
                    for(int i = 0; i < roleArray.length; i++) {
                        roleArray[i] = supplier[i];
                        //JOptionPane.showMessageDialog(this,array[i]);
                    }
                    break;
                case "Insurance":
                    roleArray = new String[insurance.length];
                    for(int i = 0; i < roleArray.length; i++) {
                        roleArray[i] = insurance[i];
                        //JOptionPane.showMessageDialog(this,array[i]);
                    }
                    break;    
        }
            //roleArray = new String[9];
            //JOptionPane.showMessageDialog(this,doctorData.size());
//            for(int i = 0; i < roleArray.length; i++) {
//                roleArray[i] = commData.get(i).getHospital().toString();
//                //JOptionPane.showMessageDialog(this,array[i]);
//            }
           
        }
        if(roleArray.length>0){
            RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(roleArray));
        }
        
                switch (OrgComboBox.getSelectedItem().toString()){
            case "Hospital":
                jLabel15.setVisible(true);
                jComboBox1.setVisible(true);
                break;
            case "Pharmacy":
                jLabel15.setVisible(true);
                jComboBox1.setVisible(true);
                break;
            case "Supplier":
                jLabel15.setVisible(true);
                jComboBox1.setVisible(true);
                break;
                
            case "Insurance":
                jLabel15.setVisible(true);
                jComboBox1.setVisible(true);
                
                break;
            default:
                jLabel15.setVisible(false);
                jComboBox1.setVisible(false);
        }

        
    }//GEN-LAST:event_OrgComboBoxActionPerformed

    private void RoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleComboBoxActionPerformed
        // TODO add your handling code here:
 
        
        
        
        
        
       



                
//        String[] roleArray = null;
//        JOptionPane.showMessageDialog(this,"hi");                  
//                        
//                //patient, doctor, hospitalAdmin, insuranceAdmin, insuranceEmp, insuranceFinance, pharmacyAdmin, supplier, sysAdmin
//                //String[]
//        String org_ = OrgComboBox.getSelectedItem().toString();
//        JOptionPane.showMessageDialog(this,org_);
//        if (org_!= null){
//            String[] patient ={"Patient"};
//            String[] hospital ={"Doctor", "HospitalAdmin"};
//            String[] system ={"SystemAdmin"};
//            String[] insurance ={"InsuranceAdmin","InsuranceEmployee","InsuranceFinance"};
//            String[] supplier ={"Supplier"};
//            String[] pharmacy ={"PharmacyAdmin"};
//                    //ArrayList<community> commData= communityData.SearchCommunity(jComboBox2.getSelectedItem().toString(), "community");
//            switch (org_){
//                case "Patient":
//                    roleArray = new String[patient.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = patient[i];
//                        JOptionPane.showMessageDialog(this,roleArray[i]);
//                    }
//                    break;
//                case "System":
//                    
//                    roleArray = new String[system.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = system[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;
//                case "Hospital":
//                    roleArray = new String[hospital.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = hospital[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    
//                    break;
//                case "Pharmacy":
//                    roleArray = new String[pharmacy.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = pharmacy[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;
//                case "Supplier":
//                    roleArray = new String[supplier.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = supplier[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;
//                case "Insurance":
//                    roleArray = new String[insurance.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = insurance[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;    
//        }
//            //roleArray = new String[9];
//            //JOptionPane.showMessageDialog(this,doctorData.size());
////            for(int i = 0; i < roleArray.length; i++) {
////                roleArray[i] = commData.get(i).getHospital().toString();
////                //JOptionPane.showMessageDialog(this,array[i]);
////            }
//           
//        }
//        if(roleArray.length>0){
//            RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(roleArray));
//        }
    }//GEN-LAST:event_RoleComboBoxActionPerformed

    private void RoleComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoleComboBoxMouseClicked
        // TODO add your handling code here:
        
               
        //JOptionPane.showMessageDialog(this,"hii");
        HospitalData hosData = new HospitalData();
        ArrayList<String> hosArr = new ArrayList<String>();
        
        InsuranceAgencyData insData = new InsuranceAgencyData();
        ArrayList<String> insArr = new ArrayList<String>();
        
        SupplierData supData = new SupplierData();
        ArrayList<String> supArr = new ArrayList<String>();
        
        pharmacyData pData = new pharmacyData();
        ArrayList<String> pArr = new ArrayList<String>();
        
        jComboBox1.removeAllItems();
        String role =OrgComboBox.getSelectedItem().toString();
        switch (role){
            case "Hospital":
                hosArr = hosData.getHospitalsInDb();
                String[] objects = new String[hosArr.size()];
 
                for (int i = 0; i < hosArr.size(); i++) {
                    objects[i] = hosArr.get(i);
                }
                //JOptionPane.showMessageDialog(this,objects[1]);
                if(objects.length >0){
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(objects));
        }
                break;
            case "Pharmacy":
                pArr = pData.getPharInDb();
                String[] object1 = new String[pArr.size()];
 
                for (int i = 0; i < pArr.size(); i++) {
                    object1[i] = pArr.get(i);
                }
                //JOptionPane.showMessageDialog(this,objects[1]);
                if(object1.length >0){
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(object1));
        }
                break;
            case "Supplier":
                supArr = supData.getSupInDb();
                String[] object2 = new String[supArr.size()];
 
                for (int i = 0; i < supArr.size(); i++) {
                    object2[i] = supArr.get(i);
                }
                
                if(object2.length >0){
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(object2));
        }
                break;
                
            case "Insurance":
                insArr = insData.getInsInDb();
                String[] object3 = new String[insArr.size()];
 
                for (int i = 0; i < insArr.size(); i++) {
                    object3[i] = insArr.get(i);
                }
                if(object3.length >0){
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(object3));
        }
                break;
            default:
                //JOptionPane.showMessageDialog(this,"hii");
                break;
        }
//        String[] roleArray = null;
//        //JOptionPane.showMessageDialog(this,"hi");                  
//                        
//                //patient, doctor, hospitalAdmin, insuranceAdmin, insuranceEmp, insuranceFinance, pharmacyAdmin, supplier, sysAdmin
//                //String[]
//        String org_ = OrgComboBox.getSelectedItem().toString();
//        //JOptionPane.showMessageDialog(this,org_);
//        if (org_!= null){
//            String[] patient ={"Patient"};
//            String[] hospital ={"Doctor", "HospitalAdmin"};
//            String[] system ={"SystemAdmin"};
//            String[] insurance ={"InsuranceAdmin","InsuranceEmployee","InsuranceFinance"};
//            String[] supplier ={"Supplier"};
//            String[] pharmacy ={"PharmacyAdmin"};
//                    //ArrayList<community> commData= communityData.SearchCommunity(jComboBox2.getSelectedItem().toString(), "community");
//            switch (org_){
//                case "Patient":
//                    roleArray = new String[patient.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = patient[i];
//                        //JOptionPane.showMessageDialog(this,roleArray[i]);
//                    }
//                    break;
//                case "System":
//                    
//                    roleArray = new String[system.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = system[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;
//                case "Hospital":
//                    roleArray = new String[hospital.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = hospital[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    
//                    break;
//                case "Pharmacy":
//                    roleArray = new String[pharmacy.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = pharmacy[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;
//                case "Supplier":
//                    roleArray = new String[supplier.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = supplier[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;
//                case "Insurance":
//                    roleArray = new String[insurance.length];
//                    for(int i = 0; i < roleArray.length; i++) {
//                        roleArray[i] = insurance[i];
//                        //JOptionPane.showMessageDialog(this,array[i]);
//                    }
//                    break;    
//        }
//            //roleArray = new String[9];
//            //JOptionPane.showMessageDialog(this,doctorData.size());
////            for(int i = 0; i < roleArray.length; i++) {
////                roleArray[i] = commData.get(i).getHospital().toString();
////                //JOptionPane.showMessageDialog(this,array[i]);
////            }
//           
//        }
//        if(roleArray.length>0){
//            RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(roleArray));
//        }
    }//GEN-LAST:event_RoleComboBoxMouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
   private void clearData() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        txtUsername.setText("");
        txtPassword.setText("");
        txtFName.setText("");
        txtLName.setText("");
        txtDOB.setText("");
        jComboBox2.setSelectedIndex(0);
        txtEmail.setText("");
        txtPhnNo.setText("");
        OrgComboBox.setSelectedIndex(0);
        String[] roleArray = null;
        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(roleArray));
        jComboBox1.setSelectedIndex(0);
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> OrgComboBox;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhnNo;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
