/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI;

import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import Model.Encounter;
import Model.EncounterData;
import Model.Doctor;
import Model.DoctorData;

/**
 *
 * @author lokeshbalamurugan
 */
public class HospitalAdminHome extends javax.swing.JPanel {

    /** Creates new form HospitalAdminHome */
    Color MouseEnterColor = new Color(255,102,102);
    Color MouseExitColor = new Color(153,204,255);
    EncounterData encData;
    DoctorData docData;
    String username;
    public HospitalAdminHome(String username) {
        initComponents();
        this.username = username;
        this.encData = new EncounterData();
        this.docData = new DoctorData();
        populateEncounterTable();
        populateDoctorTable();
    }
    
    private void populateEncounterTable() {
        DefaultTableModel model = (DefaultTableModel) PatientTable.getModel();
        model.setRowCount(0);

        for (Encounter encounter : encData.getEncounterDataFromDb()) {
            Object[] row = {encounter.getPatientUsername(), encounter.getBp(), encounter.getTemp(), encounter.getPulse()};
//            row[0] = hospital.getName();
//            row[1] = hospital.getCity();
//            row[2] = hospital.getAddress();

            model.addRow(row);
        }
    }
    
    private void populateDoctorTable() {
        DefaultTableModel model = (DefaultTableModel) DoctorTable.getModel();
        model.setRowCount(0);

        for (Doctor doctor : docData.getDoctorDataFromDb()) {
            Object[] row = {doctor.getName(), doctor.getSpecialisation()};
//            row[0] = hospital.getName();
//            row[1] = hospital.getCity();
//            row[2] = hospital.getAddress();

            model.addRow(row);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ManageDoctorJPanel = new javax.swing.JPanel();
        lblCreateUser = new javax.swing.JLabel();
        ViewEncounters = new javax.swing.JPanel();
        lblViewEncounter = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        DoctorTable = new javax.swing.JTable();
        lblUT = new javax.swing.JLabel();
        lblST = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/Very-Basic-Menu-icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/PngItem_1985212-2.png"))); // NOI18N
        jLabel2.setText(" Welcome Hospital Admin!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("l");

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOSPITAL");

        jLabel5.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME MANAGEMENT");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/User-Interface-Menu-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        ManageDoctorJPanel.setBackground(new java.awt.Color(153, 204, 255));
        ManageDoctorJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageDoctorJPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageDoctorJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageDoctorJPanelMouseExited(evt);
            }
        });

        lblCreateUser.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        lblCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateUser.setText("MANAGE DOCTOR");
        lblCreateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreateUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreateUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ManageDoctorJPanelLayout = new javax.swing.GroupLayout(ManageDoctorJPanel);
        ManageDoctorJPanel.setLayout(ManageDoctorJPanelLayout);
        ManageDoctorJPanelLayout.setHorizontalGroup(
            ManageDoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageDoctorJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreateUser)
                .addGap(43, 43, 43))
        );
        ManageDoctorJPanelLayout.setVerticalGroup(
            ManageDoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDoctorJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCreateUser)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ViewEncounters.setBackground(new java.awt.Color(153, 204, 255));
        ViewEncounters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewEncountersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewEncountersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewEncountersMouseExited(evt);
            }
        });

        lblViewEncounter.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        lblViewEncounter.setForeground(new java.awt.Color(255, 255, 255));
        lblViewEncounter.setText("VIEW ENCOUNTERS");
        lblViewEncounter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewEncounterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ViewEncountersLayout = new javax.swing.GroupLayout(ViewEncounters);
        ViewEncounters.setLayout(ViewEncountersLayout);
        ViewEncountersLayout.setHorizontalGroup(
            ViewEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewEncountersLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblViewEncounter)
                .addGap(34, 34, 34))
        );
        ViewEncountersLayout.setVerticalGroup(
            ViewEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewEncountersLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblViewEncounter)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageDoctorJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewEncounters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ManageDoctorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewEncounters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        jLabel12.setFont(new java.awt.Font("Menlo", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/Logout-icon-2.png"))); // NOI18N
        jLabel12.setText("Logout");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        PatientTable.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Blood Pressure", "Temperature", "Pulse"
            }
        ));
        jScrollPane1.setViewportView(PatientTable);

        DoctorTable.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        DoctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Specialisation"
            }
        ));
        jScrollPane4.setViewportView(DoctorTable);

        lblUT.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        lblUT.setForeground(new java.awt.Color(255, 255, 255));
        lblUT.setText("Patient Encounter Details");

        lblST.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        lblST.setForeground(new java.awt.Color(255, 255, 255));
        lblST.setText("Doctor Details");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(lblUT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblST)
                .addGap(231, 231, 231))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUT)
                    .addComponent(lblST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreateUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserMouseClicked
        // TODO add your handling code here:
        ManageDoctorPanel  mdp = new ManageDoctorPanel(username, docData);
        Login login = (Login) SwingUtilities.getRoot(this);
        login.setContentPane(mdp);
        login.invalidate();
        login.validate();
    }//GEN-LAST:event_lblCreateUserMouseClicked

    private void lblCreateUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserMouseEntered
        // TODO add your handling code here:
        lblCreateUser.setBackground(MouseEnterColor);
    }//GEN-LAST:event_lblCreateUserMouseEntered

    private void lblCreateUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserMouseExited
        // TODO add your handling code here:
        lblCreateUser.setBackground(MouseExitColor);
    }//GEN-LAST:event_lblCreateUserMouseExited

    private void ManageDoctorJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageDoctorJPanelMouseClicked
        // TODO add your handling code here:
        ManageDoctorPanel  mdp = new ManageDoctorPanel(username, docData);
        Login login = (Login) SwingUtilities.getRoot(this);
        login.setContentPane(mdp);
        login.invalidate();
        login.validate();
    }//GEN-LAST:event_ManageDoctorJPanelMouseClicked

    private void ManageDoctorJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageDoctorJPanelMouseEntered
        // TODO add your handling code here:
        ManageDoctorJPanel.setBackground(MouseEnterColor);
    }//GEN-LAST:event_ManageDoctorJPanelMouseEntered

    private void ManageDoctorJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageDoctorJPanelMouseExited
        // TODO add your handling code here:
        ManageDoctorJPanel.setBackground(MouseExitColor);
    }//GEN-LAST:event_ManageDoctorJPanelMouseExited

    private void ViewEncountersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewEncountersMouseClicked
        // TODO add your handling code here:
        VEncounterAdmin  vea = new VEncounterAdmin(username);
        Login login = (Login) SwingUtilities.getRoot(this);
        login.setContentPane(vea);
        login.invalidate();
        login.validate();
    }//GEN-LAST:event_ViewEncountersMouseClicked

    private void ViewEncountersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewEncountersMouseEntered
        // TODO add your handling code here:
        ViewEncounters.setBackground(MouseEnterColor);
    }//GEN-LAST:event_ViewEncountersMouseEntered

    private void ViewEncountersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewEncountersMouseExited
        // TODO add your handling code here:
        ViewEncounters.setBackground(MouseExitColor);
    }//GEN-LAST:event_ViewEncountersMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Login login1 = new Login();
        Login login = (Login) SwingUtilities.getRoot(this);
        login1.setVisible(true);
        login.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void lblViewEncounterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewEncounterMouseClicked
        // TODO add your handling code here:
        VEncounterAdmin  vea = new VEncounterAdmin(username);
        Login login = (Login) SwingUtilities.getRoot(this);
        login.setContentPane(vea);
        login.invalidate();
        login.validate();
    }//GEN-LAST:event_lblViewEncounterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoctorTable;
    private javax.swing.JPanel ManageDoctorJPanel;
    private javax.swing.JTable PatientTable;
    private javax.swing.JPanel ViewEncounters;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCreateUser;
    private javax.swing.JLabel lblST;
    private javax.swing.JLabel lblUT;
    private javax.swing.JLabel lblViewEncounter;
    // End of variables declaration//GEN-END:variables

}
