/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.HospitalData;
import Model.SupplierData;
import Model.UserData;
import Model.pharmacyData;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author lokeshbalamurugan
 */
public class ManageHospital extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospital
     */
    UserData userData;
    HospitalData hosData;
    pharmacyData pharmData;
    SupplierData suppData;
    Color MouseEnterColor = new Color(255,102,102);
    Color MouseExitColor = new Color(153,204,255);
    public ManageHospital(UserData userData, HospitalData hosData, pharmacyData pharmData, SupplierData suppData) {
        initComponents();
        this.userData = userData;
        this.hosData = hosData;
        this.pharmData = pharmData;
        this.suppData = suppData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        CreateHospitalJPanel = new javax.swing.JPanel();
        lblUserCreate = new javax.swing.JLabel();
        ViewHospitalJPanel = new javax.swing.JPanel();
        UserViewlbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/Very-Basic-Menu-icon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("l");

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOSPITAL");

        jLabel5.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MANAGEMENT");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/Arrows-Forward-icon-2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Menlo", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOSPITAL MANAGEMENT");

        jLabel7.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/Users-icon.png"))); // NOI18N
        jLabel7.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));

        CreateHospitalJPanel.setBackground(new java.awt.Color(153, 204, 255));
        CreateHospitalJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateHospitalJPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateHospitalJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateHospitalJPanelMouseExited(evt);
            }
        });

        lblUserCreate.setBackground(new java.awt.Color(255, 255, 255));
        lblUserCreate.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        lblUserCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblUserCreate.setText("REGISTER HOSPITAL");
        lblUserCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserCreateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CreateHospitalJPanelLayout = new javax.swing.GroupLayout(CreateHospitalJPanel);
        CreateHospitalJPanel.setLayout(CreateHospitalJPanelLayout);
        CreateHospitalJPanelLayout.setHorizontalGroup(
            CreateHospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateHospitalJPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblUserCreate)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        CreateHospitalJPanelLayout.setVerticalGroup(
            CreateHospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateHospitalJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUserCreate)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ViewHospitalJPanel.setBackground(new java.awt.Color(153, 204, 255));
        ViewHospitalJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewHospitalJPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewHospitalJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewHospitalJPanelMouseExited(evt);
            }
        });

        UserViewlbl.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        UserViewlbl.setForeground(new java.awt.Color(255, 255, 255));
        UserViewlbl.setText("VIEW HOSPITAL");
        UserViewlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserViewlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserViewlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserViewlblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ViewHospitalJPanelLayout = new javax.swing.GroupLayout(ViewHospitalJPanel);
        ViewHospitalJPanel.setLayout(ViewHospitalJPanelLayout);
        ViewHospitalJPanelLayout.setHorizontalGroup(
            ViewHospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewHospitalJPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(UserViewlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewHospitalJPanelLayout.setVerticalGroup(
            ViewHospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewHospitalJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(UserViewlbl)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 204, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/back-icon.png"))); // NOI18N
        jLabel8.setText("GO BACK");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateHospitalJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ViewHospitalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(CreateHospitalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ViewHospitalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jSplitPane1.setLeftComponent(jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ICONS/Hospital building-amico-2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1478, Short.MAX_VALUE)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserCreateMouseClicked
        // TODO add your handling code here:
        RegisterHospital rh = new RegisterHospital();
        jSplitPane1.setRightComponent(rh);
    }//GEN-LAST:event_lblUserCreateMouseClicked

    private void lblUserCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserCreateMouseEntered
        // TODO add your handling code here:
        lblUserCreate.setBackground(MouseEnterColor);
    }//GEN-LAST:event_lblUserCreateMouseEntered

    private void lblUserCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserCreateMouseExited
        // TODO add your handling code here:
        lblUserCreate.setBackground(MouseExitColor);
    }//GEN-LAST:event_lblUserCreateMouseExited

    private void CreateHospitalJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateHospitalJPanelMouseClicked
        // TODO add your handling code here:
        RegisterHospital rh = new RegisterHospital();
        jSplitPane1.setRightComponent(rh);
    }//GEN-LAST:event_CreateHospitalJPanelMouseClicked

    private void CreateHospitalJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateHospitalJPanelMouseEntered
        // TODO add your handling code here:
        CreateHospitalJPanel.setBackground(MouseEnterColor);
    }//GEN-LAST:event_CreateHospitalJPanelMouseEntered

    private void CreateHospitalJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateHospitalJPanelMouseExited
        // TODO add your handling code here:
        CreateHospitalJPanel.setBackground(MouseExitColor);
    }//GEN-LAST:event_CreateHospitalJPanelMouseExited

    private void UserViewlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserViewlblMouseClicked
        // TODO add your handling code here:
        ViewHospitalAdmin vha = new ViewHospitalAdmin(hosData);
        jSplitPane1.setRightComponent(vha);
    }//GEN-LAST:event_UserViewlblMouseClicked

    private void UserViewlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserViewlblMouseEntered
        // TODO add your handling code here:
        UserViewlbl.setBackground(MouseEnterColor);
    }//GEN-LAST:event_UserViewlblMouseEntered

    private void UserViewlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserViewlblMouseExited
        // TODO add your handling code here:
        UserViewlbl.setBackground(MouseExitColor);
    }//GEN-LAST:event_UserViewlblMouseExited

    private void ViewHospitalJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewHospitalJPanelMouseClicked
        // TODO add your handling code here:
        ViewHospitalAdmin vha = new ViewHospitalAdmin(hosData);
        jSplitPane1.setRightComponent(vha);
    }//GEN-LAST:event_ViewHospitalJPanelMouseClicked

    private void ViewHospitalJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewHospitalJPanelMouseEntered
        // TODO add your handling code here:
        ViewHospitalJPanel.setBackground(MouseEnterColor);
    }//GEN-LAST:event_ViewHospitalJPanelMouseEntered

    private void ViewHospitalJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewHospitalJPanelMouseExited
        // TODO add your handling code here:
        ViewHospitalJPanel.setBackground(MouseExitColor);
    }//GEN-LAST:event_ViewHospitalJPanelMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        AdminHome  ah = new AdminHome(userData, hosData, pharmData, suppData);
        Login login = (Login) SwingUtilities.getRoot(this);
        login.setContentPane(ah);
        login.invalidate();
        login.validate();
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateHospitalJPanel;
    private javax.swing.JLabel UserViewlbl;
    private javax.swing.JPanel ViewHospitalJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblUserCreate;
    // End of variables declaration//GEN-END:variables
}
